/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ist_project;

import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Surji
 */
public class reports extends javax.swing.JFrame {

    /**
     * Creates new form reports
     */
    public reports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appStatus = new javax.swing.JButton();
        studplac = new javax.swing.JButton();
        studplac1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reports");
        setBounds(new java.awt.Rectangle(200, 200, 200, 200));
        setPreferredSize(new java.awt.Dimension(317, 200));
        setSize(new java.awt.Dimension(317, 200));

        appStatus.setText("Student Job Application Status");
        appStatus.setMaximumSize(new java.awt.Dimension(219, 23));
        appStatus.setMinimumSize(new java.awt.Dimension(219, 23));
        appStatus.setPreferredSize(new java.awt.Dimension(219, 23));
        appStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appStatusActionPerformed(evt);
            }
        });

        studplac.setText("Number of Students Placed per Course");
        studplac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studplacActionPerformed(evt);
            }
        });

        studplac1.setText("Number of Students per Course");
        studplac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studplac1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studplac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studplac1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(appStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studplac1)
                .addGap(18, 18, 18)
                .addComponent(studplac)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appStatusActionPerformed
        try {
            String[] columns = new String[] {
                "Application Id", "Job Name", "Student Name", "Email","Contact","Major","Graduation Date","GPA","Job Status"
            };
            JFrame frame1;
            frame1 = new JFrame("Student Job Application Status");
            frame1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame1.setBounds(200, 200, 200, 200);
            frame1.setLayout(new BorderLayout()); 
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columns);
            JTable table = new JTable();
            table.setModel(model);
            JScrollPane scroll = new JScrollPane(table);
            scroll.setHorizontalScrollBarPolicy(
                    JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            scroll.setVerticalScrollBarPolicy(
                    JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost\\SQLEXPRESS:1433;database=IST659Project";
            Connection con=DriverManager.getConnection(url,"sa","root");
            Statement stmt = con.createStatement();
            String SQL = "select appj.applicationId,jb.jobName,stud.studentName,stud.email,stud.contact,stud.major,stud.expectedGraduation,stud.currentGPA,appj.jobStatus\n" +
                            "FROM (select * from dbo.appliedjobs) appj JOIN (select * from dbo.student) stud on appj.studentId = stud.studentId\n" +
                            "JOIN (select * from dbo.jobs) jb on appj.jobId=jb.jobId;";
            ResultSet rs = stmt.executeQuery(SQL);
            int i =0;
            while(rs.next())
            {
                String appid = rs.getString("applicationId");
                String jobname = rs.getString("jobName");
                String studname = rs.getString("studentName");
                String email = rs.getString("email"); 
                String cont = rs.getString("contact");
                String maj = rs.getString("major");
                String graddate = rs.getString("expectedGraduation");
                String gpa = rs.getString("currentGPA");
                String jstatus = rs.getString("jobStatus");
                model.addRow(new Object[]{appid, jobname, studname, email, cont, maj, graddate,gpa,jstatus });
                i++; 
                frame1.add(scroll);
                frame1.setVisible(true);
                frame1.setSize(800,500);
            }
            if(i <1)
            {
                JOptionPane.showMessageDialog(null, "No Records Found","Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_appStatusActionPerformed

    private void studplac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studplac1ActionPerformed
        try {
            String[] columns = new String[] {
                "Course", "Number of Students"
            };
            JFrame frame1;
            frame1 = new JFrame("Number of Students per Course");
            frame1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame1.setBounds(200, 200, 200, 200);
            frame1.setLayout(new BorderLayout()); 
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columns);
            JTable table = new JTable();
            table.setModel(model);
            JScrollPane scroll = new JScrollPane(table);
            scroll.setHorizontalScrollBarPolicy(
                    JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            scroll.setVerticalScrollBarPolicy(
                    JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost\\SQLEXPRESS:1433;database=IST659Project";
            Connection con=DriverManager.getConnection(url,"sa","root");
            Statement stmt = con.createStatement();
            String SQL = "select count(*) as cnt,major from dbo.student group by major;";
            ResultSet rs = stmt.executeQuery(SQL);
            int i =0;
            while(rs.next())
            {
                String cnt = rs.getString("cnt");
                String maj = rs.getString("major");
                model.addRow(new Object[]{maj, cnt});
                i++; 
                frame1.add(scroll);
                frame1.setVisible(true);
                frame1.setSize(800,500);
            }
            if(i <1)
            {
                JOptionPane.showMessageDialog(null, "No Records Found","Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studplac1ActionPerformed

    private void studplacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studplacActionPerformed
        try {
            String[] columns = new String[] {
                "Course", "Number of Students Placed"
            };
            JFrame frame1;
            frame1 = new JFrame("Number of Students per Course");
            frame1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame1.setBounds(200, 200, 200, 200);
            frame1.setLayout(new BorderLayout()); 
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columns);
            JTable table = new JTable();
            table.setModel(model);
            JScrollPane scroll = new JScrollPane(table);
            scroll.setHorizontalScrollBarPolicy(
                    JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            scroll.setVerticalScrollBarPolicy(
                    JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost\\SQLEXPRESS:1433;database=IST659Project";
            Connection con=DriverManager.getConnection(url,"sa","root");
            Statement stmt = con.createStatement();
            String SQL = "select count(stud.studentName) as cnt,stud.major\n" +
                "FROM (select * from dbo.appliedjobs) appj JOIN (select * from dbo.student) stud on appj.studentId = stud.studentId where appj.jobStatus='accepted'\n" +
                "group by stud.major;";
            ResultSet rs = stmt.executeQuery(SQL);
            int i =0;
            while(rs.next())
            {
                String cnt = rs.getString("cnt");
                String maj = rs.getString("major");
                model.addRow(new Object[]{maj, cnt});
                i++; 
                frame1.add(scroll);
                frame1.setVisible(true);
                frame1.setSize(800,500);
            }
            if(i <1)
            {
                JOptionPane.showMessageDialog(null, "No Records Found","Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(reports.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studplacActionPerformed

    /**
     * @param args the command line arguments
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reports().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appStatus;
    private javax.swing.JButton studplac;
    private javax.swing.JButton studplac1;
    // End of variables declaration//GEN-END:variables
}
